let catalogs=null;let latestPlan=null;let measuredDemo=null;const $=s=>document.querySelector(s);const all=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=(form,name)=>Number(form.elements[name].value);
const range=m=>`${Math.round(m.low).toLocaleString('it-IT')}–${Math.round(m.high).toLocaleString('it-IT')}`;
const labels={POTENTIAL_FIT:'Candidato promettente',UNLIKELY_FIT:'Da verificare con cautela',NOT_FEASIBLE:'Non fattibile'};

async function init(){
  catalogs=await fetch('/api/catalog').then(r=>r.json());
  $('#hardware-options').innerHTML=catalogs.hardware.items.map((v,i)=>`<label class="check"><input type="checkbox" name="hardware" value="${esc(v.id)}" checked><span>${esc(v.name)}<small> · ${v.memory_gib} GB · ${v.power_w} W</small></span></label>`).join('');
  $('#model-options').innerHTML=catalogs.models.items.map((v,i)=>`<label class="check"><input type="checkbox" name="model" value="${esc(v.id)}" ${i<3?'checked':''}><span>${esc(v.name)}</span></label>`).join('');
}

function intakeFromForm(){
  const f=$('#intake-form');
  return {schema:'srh.client-intake.v1',id:f.elements.id.value.trim(),name:f.elements.name.value.trim(),description:'Assessment captured in an SRH client meeting.',workload_class:f.elements.workload_class.value,reasoning:'disabled',
    traffic:{total_users:num(f,'total_users'),concurrent_users:num(f,'concurrent_users'),requests_per_day:num(f,'requests_per_day'),peak_requests_per_minute:num(f,'peak_rpm'),burst_factor:2},
    documents:{context_mode:f.elements.context_mode.value,pages:{p50:num(f,'pages_p50'),p95:num(f,'pages_p95'),max:num(f,'pages_max')},retrieved_pages:{p50:num(f,'retrieved_p50'),p95:num(f,'retrieved_p95'),max:num(f,'retrieved_max')},scanned_fraction:num(f,'scanned_percent')/100,shared_prefix_probability:.4,repeated_context_probability:.3},
    responses:{words:{p50:num(f,'words_p50'),p95:num(f,'words_p95'),max:num(f,'words_max')}},
    experience:{first_useful_response_seconds:num(f,'first_seconds'),complete_response_seconds:num(f,'complete_seconds'),error_rate_max:.01},
    quality:{grounding_required:f.elements.grounding.checked,citation_required:f.elements.citations.checked,structured_output_required:true,minimum_score:.95},
    deployment:{data_residency:f.elements.data_residency.value,maximum_device_power_w:num(f,'max_power')},
    exploration:{hardware_ids:all('[name=hardware]:checked').map(v=>v.value),model_ids:all('[name=model]:checked').map(v=>v.value),requested_model_families:f.elements.requested_models.value.split(',').map(v=>v.trim()).filter(Boolean),weight_bits:all('[name=bits]:checked').map(v=>Number(v.value))},
    translation_assumptions:{words_per_page:450,tokens_per_word:1.34,prompt_overhead_tokens:256}};
}

function setForm(v){const f=$('#intake-form');const set=(n,x)=>{if(f.elements[n])f.elements[n].value=x};set('name',v.name);set('id',v.id);set('workload_class',v.workload_class);set('data_residency',v.deployment.data_residency);set('requested_models',(v.exploration.requested_model_families||[]).join(', '));set('context_mode',v.documents.context_mode);set('scanned_percent',v.documents.scanned_fraction*100);set('total_users',v.traffic.total_users);set('concurrent_users',v.traffic.concurrent_users);set('requests_per_day',v.traffic.requests_per_day);set('peak_rpm',v.traffic.peak_requests_per_minute);for(const [prefix,d] of [['pages',v.documents.pages],['retrieved',v.documents.retrieved_pages],['words',v.responses.words]])for(const k of ['p50','p95','max'])set(`${prefix}_${k}`,d[k]);set('first_seconds',v.experience.first_useful_response_seconds);set('complete_seconds',v.experience.complete_response_seconds);set('max_power',v.deployment.maximum_device_power_w);all('[name=hardware]').forEach(x=>x.checked=v.exploration.hardware_ids.includes(x.value));all('[name=model]').forEach(x=>x.checked=v.exploration.model_ids.includes(x.value));all('[name=bits]').forEach(x=>x.checked=v.exploration.weight_bits.includes(Number(x.value)));}

function render(plan){
  latestPlan=plan;const c=plan.translated_workload_contract;const shortlist=new Set(plan.screening_summary.shortlist_candidate_ids);
  $('#translated').innerHTML=[['Utenti simultanei',Math.max(...c.traffic.concurrent_users)],['Input tipico',`${c.request_profile.input_tokens.p50.toLocaleString('it-IT')} token`],['Input impegnativo',`${c.request_profile.input_tokens.p95.toLocaleString('it-IT')} token`],['Risposta completa',`${c.service_objectives.end_to_end_p95_ms/1000} secondi`]].map(([l,v])=>`<div class="stat"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('');
  const rows=plan.candidates.filter(v=>shortlist.has(v.candidate_id));const seconds=m=>`${(m.low/1000).toLocaleString('it-IT',{maximumFractionDigits:1})}–${(m.high/1000).toLocaleString('it-IT',{maximumFractionDigits:1})}`;
  const candidateRow=v=>{const m=v.performance_projection.metrics,cap=v.capacity,cls=v.screening_status==='POTENTIAL_FIT'?'potential':v.screening_status==='NOT_FEASIBLE'?'blocked':'unlikely';return `<tr><td><strong>${esc(v.hardware.name)}</strong><br><small>${v.hardware.power_w} W · ${esc(v.hardware.class)}</small></td><td>${esc(v.model.name)}<br><small>${v.weight_bits} bit · ${esc(v.model.architecture)}</small></td><td>${cap.estimated_total_required_gib} / ${cap.usable_memory_gib} GiB<br><small>${cap.estimated_headroom_gib} GiB margine</small></td><td class="metric-range">${seconds(m.ttfa_p95_ms)} s<small>stima ±45%</small></td><td class="metric-range">${seconds(m.end_to_end_p95_ms)} s<small>stima ±45%</small></td><td><span class="badge ${cls}">${labels[v.screening_status]}</span><br><small>${v.blockers.length?esc(v.blockers.join(', ')):'Misura richiesta'}</small></td></tr>`};
  const table=values=>`<table><thead><tr><th>Ambiente</th><th>Classe modello</th><th>Memoria</th><th>Prima risposta stimata</th><th>Risposta completa stimata</th><th>Stato</th></tr></thead><tbody>${values.map(candidateRow).join('')}</tbody></table>`;
  $('#shortlist').innerHTML=`<p class="result-explainer"><strong>${rows.length} candidati da portare al benchmark.</strong> La selezione copre le classi di modello richieste e, quando possibile, ambienti hardware diversi.</p>${table(rows)}`;
  const selectedModels=plan.client_inputs.exploration.model_ids;
  const coverage=selectedModels.map(id=>{const values=plan.candidates.filter(v=>v.model.id===id),feasible=values.filter(v=>v.screening_status!=='NOT_FEASIBLE'),picked=values.filter(v=>shortlist.has(v.candidate_id));return {name:values[0]?.model.name||id,total:values.length,feasible:feasible.length,picked:picked.length,best:feasible[0]||values[0]}});
  $('#model-coverage').innerHTML=`<h3>Copertura delle classi selezionate</h3><div class="coverage-grid">${coverage.map(v=>`<div class="coverage-card"><strong>${esc(v.name)}</strong><span>${v.feasible?v.picked+' candidato/i in shortlist':"Nessuna combinazione fattibile"}</span><small>${v.feasible?`${v.feasible} combinazioni superano capacità, contesto e potenza`:`Migliore tentativo: ${esc(v.best?.blockers.join(', ')||'non disponibile')}`}</small></div>`).join('')}</div>`;
  $('#candidate-matrix').innerHTML=table(plan.candidates);
  const ex=plan.benchmark_handoff.experiment_plan.experiments;
  const purpose={"baseline-p50-c1":"Misura la risposta tipica con un utente.","tail-p95-c1":"Misura un documento impegnativo con un utente.","max-envelope-c1":"Verifica il massimo dichiarato.","cold-p95-c1":"Misura il caso senza riuso della cache."};
  $('#test-plan').innerHTML=`<p><strong>${ex.length} prove</strong> per ciascun candidato selezionato:</p><ol>${ex.slice(0,6).map(v=>`<li>${esc(purpose[v.experiment_id]||(v.experiment_id.startsWith('concurrency-')?'Misura il carico con più utenti contemporanei.':'Misura il riuso di documenti e contesti ripetuti.'))} <small>(${v.request.input_tokens.toLocaleString('it-IT')} in / ${v.request.output_tokens.toLocaleString('it-IT')} out, ${v.concurrency} ${v.concurrency===1?'utente':'utenti'})</small></li>`).join('')}${ex.length>6?`<li>+ ${ex.length-6} ulteriori condizioni di coda e riuso</li>`:''}</ol>`;
  const families=plan.benchmark_handoff.requested_model_families||[];
  $('#assumptions').innerHTML=`<ul><li>Token derivati da pagine e parole dichiarate.</li><li>${Math.round(plan.client_inputs.documents.scanned_fraction*100)}% dei documenti dichiarati come scansioni.</li><li>Famiglie richieste: ${families.length?families.map(esc).join(', '):'da definire'}.</li><li>Prestazioni: fascia euristica a bassa confidenza.</li><li>Qualità, OCR e retrieval non sono simulati.</li><li>${plan.historical_evidence_coverage.length} evidenza storica SRH pertinente all’hardware selezionato.</li><li>Esito finale solo dopo benchmark osservato.</li></ul>`;
  $('#results').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth'});
}

$('#intake-form').addEventListener('submit',async e=>{e.preventDefault();$('#error').classList.add('hidden');try{const response=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(intakeFromForm())});const data=await response.json();if(!response.ok)throw new Error(data.error||'Errore di pianificazione');render(data)}catch(err){$('#error').textContent=err.message;$('#error').classList.remove('hidden')}});
$('#load-example').addEventListener('click',async()=>setForm(await fetch('/api/example').then(r=>r.json())));
$('#download-json').addEventListener('click',()=>{if(!latestPlan)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(latestPlan,null,2)],{type:'application/json'}));a.download=`${latestPlan.assessment_id}.capacity-plan.json`;a.click();URL.revokeObjectURL(a.href)});
$('#print').addEventListener('click',()=>window.print());
const readJson=file=>file.text().then(text=>JSON.parse(text));
const downloadJson=(name,value)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const selectedEvidenceFiles=()=>all('.evidence-file').flatMap(input=>[...input.files]);
const updateMeasuredFiles=()=>{if(measuredDemo){$('#measured-files').textContent=`Demo caricata: 1 manifest, 1 contratto e ${measuredDemo.evidences.length} evidenze osservate.`;return}const files=selectedEvidenceFiles();$('#measured-files').textContent=files.length?`${files.length} evidenze selezionate: ${files.map(v=>v.name).join(', ')}`:'Nessun pacchetto caricato.'};
all('#manifest-file, #measured-contract-file, .evidence-file').forEach(input=>input.addEventListener('change',()=>{measuredDemo=null;updateMeasuredFiles()}));
$('#load-measured-demo').addEventListener('click',async()=>{try{measuredDemo=await fetch('/api/measured-demo').then(r=>{if(!r.ok)throw new Error('Demo non disponibile');return r.json()});updateMeasuredFiles();$('#measured-result').innerHTML='<div class="demo-notice"><strong>Demo pronta.</strong> Usa “Valuta evidenze misurate”. I tre file provengono dalla precedente campagna SRH su GB10; il contratto è quello del test, non quello del cliente corrente.</div>'}catch(err){$('#error').textContent=err.message;$('#error').classList.remove('hidden')}});
$('#download-demo-manifest').addEventListener('click',async()=>{try{const pack=measuredDemo||await fetch('/api/measured-demo').then(r=>r.json());downloadJson('qwen-measured-demo-manifest.json',pack.manifest)}catch(err){$('#error').textContent=err.message;$('#error').classList.remove('hidden')}});
$('#evaluate-measured').addEventListener('click',async()=>{try{if(!latestPlan&&!measuredDemo)throw new Error('Calcola prima la shortlist o carica la demo misurata.');let contract,manifest,evidences;if(measuredDemo){({contract,manifest,evidences}=measuredDemo)}else{const contractFile=$('#measured-contract-file').files[0],manifestFile=$('#manifest-file').files[0],evidenceFiles=selectedEvidenceFiles();if(!manifestFile||evidenceFiles.length<2)throw new Error('Seleziona un manifest e almeno due file di evidenza nei campi separati.');contract=contractFile?await readJson(contractFile):latestPlan.translated_workload_contract;manifest=await readJson(manifestFile);evidences=await Promise.all(evidenceFiles.map(async file=>({source:file.name,evidence:await readJson(file)})))}const response=await fetch('/api/deployment-recommendation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contract,manifest,evidences})});const report=await response.json();if(!response.ok)throw new Error(report.error||'Evidenze non valutabili');const label=report.verdict==='RECOMMENDED'?'Configurazione raccomandata':report.verdict==='NO_DEPLOYMENT_MEETS_REQUIREMENTS'?'Misure valide: serve una nuova configurazione':'Confronto non ancora conclusivo';const action=report.verdict==='RECOMMENDED'?`La configurazione ${report.recommended_label} supera qualità e obiettivi; il prossimo passo è il test di accettazione sul sito cliente.`:report.verdict==='NO_DEPLOYMENT_MEETS_REQUIREMENTS'?'La qualità è stata verificata, ma nessun candidato supera tutti gli obiettivi di servizio. Modifica la shortlist o concorda un target diverso e ripeti il benchmark.':'Completa le evidenze mancanti o rendi identici scenario, evaluator, esperimento e protocollo.';const blockerLabels={ttfa_p95_ms:'prima risposta oltre target',end_to_end_p95_ms:'risposta completa oltre target',answer_tokens_per_second_min:'velocità di generazione insufficiente',error_rate_max:'troppi errori',quality_minimum_score:'qualità sotto soglia',required_quality_checks:'controlli qualità obbligatori',license_review_status:'licenza non approvata'};const candidateRows=report.candidates.map(v=>`<tr><td>${esc(v.deployment.label)}</td><td>${(v.checks.ttfa_p95_ms.actual/1000).toLocaleString('it-IT')} s</td><td>${(v.checks.end_to_end_p95_ms.actual/1000).toLocaleString('it-IT')} s</td><td>${Math.round(v.checks.quality_minimum_score.actual*100)}%</td><td>${v.eligible?'Tutti i requisiti superati':esc(v.blocking_objectives.map(x=>blockerLabels[x]||x).join('; '))}</td></tr>`).join('');$('#measured-result').innerHTML=`<div class="verified"><span>ESITO SU DATI MISURATI</span><strong>${esc(label)}</strong><p>${esc(action)}</p></div><table><thead><tr><th>Candidato</th><th>Prima risposta p95</th><th>Risposta completa p95</th><th>Qualità</th><th>Valutazione</th></tr></thead><tbody>${candidateRows}</tbody></table>`}catch(err){$('#error').textContent=err.message;$('#error').classList.remove('hidden')}});
init().catch(err=>{const box=$('#error');box.textContent=`Impossibile caricare i cataloghi: ${err.message}`;box.classList.remove('hidden')});
